name: 오류 보고서
description: 이 양식을 사용하여 오류 보고서를 작성해주세요.
title: "[버그] "
labels: ["버그"]
projects: ["Yuil-Robotics/1"]
body:
  - type: markdown
    attributes:
      value: |
        오류 개요를 이슈 제목에 작성해주세요.  
        예시) **[버그] 조작 버튼 클릭 시 무한 로딩 발생**
  - type: textarea
    id: bug-description
    attributes:
      label: 오류 발생 단계
      description: 어떤 단계에서 오류가 발생했나요?
      placeholder: 오류가 발생하기까지 수행한 단계들을 자세히 설명해주세요.
      value: "1. 앱 실행\n2. 조작 버튼 클릭\n3. 무한 로딩 발생"
    validations:
      required: true
  - type: textarea
    id: bug-symptoms
    attributes:
      label: 오류 증상
      description: 어떤 오류가 발생했나요?
      placeholder: 발생한 오류의 구체적인 증상을 설명해주세요.
      value: "화면이 멈추며 무한 로딩이 발생하고, 다른 버튼 조작이 불가능합니다."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 오류 로그 (선택)
      description: 출력된 오류 로그가 있다면 복사하여 붙여 넣어주세요.
      render: shell
    validations:
      required: false
