name: 작업 계획서
description: 이 양식을 사용하여 어떤 작업을 진행해야 하는지 설명해주세요.
title: "[작업] "
labels: ["개선"]
projects: ["jellen-server/2"]
body:
  - type: markdown
    attributes:
      value: |
        작업 개요를 이슈 제목에 작성해주세요.  
        예시) **[작업] 로봇 조작 기능 구현**
  - type: input
    id: title
    attributes:
      label: 개요
      description: 작업에 대한 간단한 개요를 작성해주세요.
      placeholder: 간단한 작업 개요
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: 진행해야 할 업무
      description: 진행해야 할 작업 모두 나열해주세요.
      value: |
        - [ ] 작업 1
        - [ ] 작업 2
        - [ ] 작업 3
    validations:
      required: true
  - type: textarea
    id: note
    attributes:
      label: 추가 내용 (선택)
      description: 더 설명할 내용이 있다면 적어주세요.
      placeholder: 추가로 설명할 내용
    validations:
      required: false
